import images from '@/assets/imgs';

import {
  GetMapByIdResponse,
  MapWithSubject,
  MasterSubject,
  Order,
  OrderDetails,
  Organization,
  SubjectWithMaster,
} from '../types';

export const masterSubjects = [
  {
    id: 'ms001',
    name: 'Khoa học Tự nhiên',
    description: 'Khám phá thế giới xung quanh qua các bài học VR sinh động và trực quan.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
  },
  {
    id: 'ms002',
    name: 'Toán học',
    description: 'Biến những công thức khô khan thành trải nghiệm học tập tương tác đầy hứng thú.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
  },
  {
    id: 'ms003',
    name: 'Lịch sử & Địa lý',
    description: 'Du hành thời gian và không gian, chứng kiến lịch sử và địa lý bằng trải nghiệm thực tế ảo.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
  },
] as MasterSubject[];

export const subjectsWithMasters = [
  {
    id: 'sub001',
    name: 'Sinh học tế bào',
    description: 'Khám phá cấu trúc tế bào và cơ chế hoạt động của sự sống.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    masterSubject: masterSubjects[0],
  },
  {
    id: 'sub002',
    name: 'Hóa học cơ bản',
    description: 'Thực hiện thí nghiệm an toàn và sinh động ngay trong thế giới ảo.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    masterSubject: masterSubjects[0],
  },
  {
    id: 'sub003',
    name: 'Đại số cơ bản',
    description: 'Khám phá phương trình và hàm số thông qua các bài toán trực quan trong không gian 3D.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    masterSubject: masterSubjects[1],
  },
  {
    id: 'sub004',
    name: 'Hình học không gian',
    description: 'Xoay, cắt, ghép các khối hình 3D để hiểu rõ bản chất của hình học.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    masterSubject: masterSubjects[1],
  },
  {
    id: 'sub005',
    name: 'Lịch sử Việt Nam',
    description: 'Trải nghiệm những thời khắc quan trọng của dân tộc qua thực tế ảo sống động.',
    imageUrl: '/images/subjects/vietnam-history.jpg',
    status: 'active',
    masterSubject: masterSubjects[2],
  },
  {
    id: 'sub006',
    name: 'Địa lý tự nhiên Việt Nam',
    description: 'Khám phá cảnh quan, khí hậu và hệ sinh thái đặc trưng của Việt Nam.',
    imageUrl: '/images/subjects/geography.jpg',
    status: 'active',
    masterSubject: masterSubjects[2],
  },
] as SubjectWithMaster[];

export const mapsWithSubjects = [
  {
    id: 'map001',
    mapCode: 'BIO-CELL-01',
    price: 199000,
    name: 'Khám phá tế bào',
    description: 'Quan sát cấu trúc tế bào trong môi trường VR sống động, nơi từng bào quan đều chuyển động chân thực.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    subject: subjectsWithMasters[0],
  },
  {
    id: 'map002',
    mapCode: 'CHEM-LAB-01',
    price: 229000,
    name: 'Phòng thí nghiệm ảo',
    description: 'Pha chế, phản ứng và quan sát hiện tượng hóa học trong môi trường an toàn và mô phỏng chính xác.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    subject: subjectsWithMasters[1],
  },
  {
    id: 'map003',
    mapCode: 'ALG-EQ-01',
    price: 179000,
    name: 'Phương trình và Hàm số',
    description: 'Tương tác với đồ thị 3D, quan sát sự thay đổi của hàm số theo từng biến số trong không gian.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    subject: subjectsWithMasters[2],
  },
  {
    id: 'map004',
    mapCode: 'GEO-3D-01',
    price: 199000,
    name: 'Khám phá hình khối 3D',
    description: 'Tạo, chia và ghép các hình học không gian bằng thao tác tay trong VR.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    subject: subjectsWithMasters[3],
  },
  {
    id: 'map005',
    mapCode: 'HIST-VN-01',
    price: 249000,
    name: 'Chiến thắng Điện Biên Phủ',
    description: 'Trở về năm 1954 và chứng kiến trận chiến lịch sử của dân tộc Việt Nam trong không gian thực tế ảo.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    subject: subjectsWithMasters[4],
  },
  {
    id: 'map006',
    mapCode: 'GEO-VN-02',
    price: 189000,
    name: 'Khám phá miền Trung Việt Nam',
    description: 'Bay qua các dãy núi, con sông và bờ biển đặc trưng của miền Trung trong VR 360°.',
    imageUrl: `${images.landingHero}`,
    status: 'active',
    subject: subjectsWithMasters[5],
  },
] as MapWithSubject[];

export const mockMapMetadata: GetMapByIdResponse = {
  id: 'map001',
  mapCode: 'SCIENCE_LAB_VR',
  price: 1200000,
  name: 'Phòng Thí Nghiệm Khoa Học Ảo',
  description:
    'Khám phá thế giới vật lý và hóa học trong môi trường 3D tương tác, giúp học sinh hiểu sâu hơn về các hiện tượng tự nhiên.',
  imageUrl: '/images/maps/science-lab-vr.jpg',
  status: 'active',
  subject: {
    id: 'subject001',
    name: 'Vật Lý Cơ Bản',
    description: 'Môn học giúp học sinh làm quen với các khái niệm cơ bản về vật lý thông qua trải nghiệm thực tế ảo.',
    imageUrl: '/images/subjects/basic-physics.jpg',
    status: 'active',
    masterSubject: {
      id: 'master001',
      name: 'Khoa Học Tự Nhiên',
      description: 'Nhóm môn học giúp học sinh khám phá các hiện tượng tự nhiên qua mô phỏng thực tế ảo.',
      imageUrl: '/images/masters/natural-science.jpg',
      status: 'active',
    },
  },
  mapObjects: [
    {
      id: 'obj001',
      mapId: 'map001',
      name: 'Ống Nghiệm',
      imageUrl: '/images/objects/test-tube.png',
      objectCode: 'OBJ_TEST_TUBE',
    },
    {
      id: 'obj002',
      mapId: 'map001',
      name: 'Cân Điện Tử',
      imageUrl: '/images/objects/digital-scale.png',
      objectCode: 'OBJ_SCALE',
    },
    {
      id: 'obj003',
      mapId: 'map001',
      name: 'Bếp Cồn',
      imageUrl: '/images/objects/burner.png',
      objectCode: 'OBJ_BURNER',
    },
    {
      id: 'obj004',
      mapId: 'map001',
      name: 'Ống Đong',
      imageUrl: '/images/objects/measuring-cylinder.png',
      objectCode: 'OBJ_CYLINDER',
    },
  ],
  taskLocations: [
    {
      id: 'loc001',
      mapId: 'map001',
      name: 'Khu Chuẩn Bị Thí Nghiệm',
      imageUrl: '/images/locations/preparation-area.jpg',
      locationCode: 'LOC_PREP',
    },
    {
      id: 'loc002',
      mapId: 'map001',
      name: 'Khu Đun Nóng',
      imageUrl: '/images/locations/heating-area.jpg',
      locationCode: 'LOC_HEAT',
    },
    {
      id: 'loc003',
      mapId: 'map001',
      name: 'Khu Pha Chế Dung Dịch',
      imageUrl: '/images/locations/mixing-area.jpg',
      locationCode: 'LOC_MIX',
    },
  ],
  createdAt: '2025-03-12T10:45:00Z',
  updatedAt: '2025-09-28T14:22:00Z',
};

export const mockOrganizations: Organization[] = [
  {
    id: 'user-001',
    name: 'Trường THPT Lê Hồng Phong',
    email: 'contact@lehongphong.edu.vn',
    role: 'organization',
    orgId: 'org-001',
    phone: '028-3910-1234',
    address: '235 Nguyễn Văn Cừ, Quận 5, TP. Hồ Chí Minh',
    macAddress: '00-14-22-01-23-45',
    activationKey: 'FPT-23092025-LEHP',
  },
  {
    id: 'user-002',
    name: 'Trường THPT Chuyên Hà Nội - Amsterdam',
    email: 'info@hn-ams.edu.vn',
    role: 'organization',
    orgId: 'org-002',
    phone: '024-3829-5678',
    address: 'Hoàng Minh Giám, Cầu Giấy, Hà Nội',
    macAddress: '00-16-4D-2B-55-9C',
    activationKey: 'HNA-24092025-AMSD',
  },
  {
    id: 'user-003',
    name: 'Trường THCS Nguyễn Du',
    email: 'nguyendu@edu.vn',
    role: 'organization',
    orgId: 'org-003',
    phone: '028-3876-4321',
    address: '12 Trần Hưng Đạo, Quận 1, TP. Hồ Chí Minh',
    macAddress: '00-26-B9-3E-8C-22',
    activationKey: 'ND-25092025-TTND',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-20251004-001',
    organizationId: 'org-0001',
    createdAtUtc: '2025-10-03T08:30:00Z',
    updatedAtUtc: '2025-10-03T09:00:00Z',
    items: 2,
    totalMoneyAmount: 2400000,
    payosOrderCode: 98123745,
    paymentMethod: 'Bank Transfer',
    bank: 'Vietcombank',
    status: 'Completed',
  },
  {
    id: 'ord-20250928-002',
    organizationId: 'org-0002',
    createdAtUtc: '2025-09-28T10:15:00Z',
    updatedAtUtc: '2025-09-28T10:45:00Z',
    items: 1,
    totalMoneyAmount: 1200000,
    payosOrderCode: 98123746,
    paymentMethod: 'Credit Card',
    bank: 'Techcombank',
    status: 'Completed',
  },
  {
    id: 'ord-20250920-003',
    organizationId: 'org-0003',
    createdAtUtc: '2025-09-20T14:00:00Z',
    updatedAtUtc: '2025-09-20T14:15:00Z',
    items: 3,
    totalMoneyAmount: 3600000,
    payosOrderCode: 98123747,
    paymentMethod: 'E-Wallet',
    bank: 'Momo',
    status: 'Pending',
  },
  {
    id: 'ord-20250910-004',
    organizationId: 'org-0004',
    createdAtUtc: '2025-09-10T09:25:00Z',
    updatedAtUtc: '2025-09-10T09:30:00Z',
    items: 1,
    totalMoneyAmount: 1000000,
    payosOrderCode: 98123748,
    paymentMethod: 'Bank Transfer',
    bank: 'BIDV',
    status: 'Cancelled',
  },
  {
    id: 'ord-20250901-005',
    organizationId: 'org-0001',
    createdAtUtc: '2025-09-01T11:00:00Z',
    updatedAtUtc: '2025-09-01T11:20:00Z',
    items: 2,
    totalMoneyAmount: 2200000,
    payosOrderCode: 98123749,
    paymentMethod: 'Credit Card',
    bank: 'ACB',
    status: 'Processing',
  },
];

export const mockOrderDetails: OrderDetails = {
  id: 'ord-20251004-001',
  organizationId: 'org-0001',
  createdAtUtc: '2025-10-03T08:30:00Z',
  updatedAtUtc: '2025-10-03T09:00:00Z',
  items: 2,
  totalMoneyAmount: 2400000,
  payosOrderCode: 98123745,
  paymentMethod: 'Bank Transfer',
  bank: 'Vietcombank',
  status: 'Completed',
  orderItems: [
    {
      id: 'map001',
      mapCode: 'SCIENCE_LAB_VR',
      price: 1200000,
      name: 'Phòng Thí Nghiệm Khoa Học Ảo',
      description:
        'Khám phá thế giới vật lý và hóa học trong môi trường 3D tương tác, giúp học sinh hiểu sâu hơn về các hiện tượng tự nhiên.',
      imageUrl: '/images/maps/science-lab-vr.jpg',
      status: 'active',
      subject: {
        id: 'subject001',
        name: 'Vật Lý Cơ Bản',
        description:
          'Môn học giúp học sinh làm quen với các khái niệm cơ bản về vật lý thông qua trải nghiệm thực tế ảo.',
        imageUrl: '/images/subjects/basic-physics.jpg',
        status: 'active',
        masterSubject: {
          id: 'master001',
          name: 'Khoa Học Tự Nhiên',
          description: 'Nhóm môn học giúp học sinh khám phá các hiện tượng tự nhiên qua mô phỏng thực tế ảo.',
          imageUrl: '/images/masters/natural-science.jpg',
          status: 'active',
        },
      },
    },
    {
      id: 'map002',
      mapCode: 'HISTORY_EXPLORER_VR',
      price: 1200000,
      name: 'Hành Trình Khám Phá Lịch Sử',
      description:
        'Trải nghiệm các thời kỳ lịch sử nổi bật của Việt Nam qua công nghệ thực tế ảo sinh động và hấp dẫn.',
      imageUrl: '/images/maps/history-explorer-vr.jpg',
      status: 'active',
      subject: {
        id: 'subject002',
        name: 'Lịch Sử Việt Nam',
        description: 'Khám phá các giai đoạn lịch sử của đất nước thông qua hình ảnh trực quan và tương tác VR.',
        imageUrl: '/images/subjects/vietnamese-history.jpg',
        status: 'active',
        masterSubject: {
          id: 'master002',
          name: 'Khoa Học Xã Hội',
          description: 'Nhóm môn học giúp học sinh hiểu rõ về xã hội, văn hóa và lịch sử Việt Nam.',
          imageUrl: '/images/masters/social-science.jpg',
          status: 'active',
        },
      },
    },
    {
      id: 'map002',
      mapCode: 'HISTORY_EXPLORER_VR',
      price: 1200000,
      name: 'Hành Trình Khám Phá Lịch Sử',
      description:
        'Trải nghiệm các thời kỳ lịch sử nổi bật của Việt Nam qua công nghệ thực tế ảo sinh động và hấp dẫn.',
      imageUrl: '/images/maps/history-explorer-vr.jpg',
      status: 'active',
      subject: {
        id: 'subject002',
        name: 'Lịch Sử Việt Nam',
        description: 'Khám phá các giai đoạn lịch sử của đất nước thông qua hình ảnh trực quan và tương tác VR.',
        imageUrl: '/images/subjects/vietnamese-history.jpg',
        status: 'active',
        masterSubject: {
          id: 'master002',
          name: 'Khoa Học Xã Hội',
          description: 'Nhóm môn học giúp học sinh hiểu rõ về xã hội, văn hóa và lịch sử Việt Nam.',
          imageUrl: '/images/masters/social-science.jpg',
          status: 'active',
        },
      },
    },
    {
      id: 'map002',
      mapCode: 'HISTORY_EXPLORER_VR',
      price: 1200000,
      name: 'Hành Trình Khám Phá Lịch Sử',
      description:
        'Trải nghiệm các thời kỳ lịch sử nổi bật của Việt Nam qua công nghệ thực tế ảo sinh động và hấp dẫn.',
      imageUrl: '/images/maps/history-explorer-vr.jpg',
      status: 'active',
      subject: {
        id: 'subject002',
        name: 'Lịch Sử Việt Nam',
        description: 'Khám phá các giai đoạn lịch sử của đất nước thông qua hình ảnh trực quan và tương tác VR.',
        imageUrl: '/images/subjects/vietnamese-history.jpg',
        status: 'active',
        masterSubject: {
          id: 'master002',
          name: 'Khoa Học Xã Hội',
          description: 'Nhóm môn học giúp học sinh hiểu rõ về xã hội, văn hóa và lịch sử Việt Nam.',
          imageUrl: '/images/masters/social-science.jpg',
          status: 'active',
        },
      },
    },
  ],
};
